<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVFnq843\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVFnq843/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVFnq843.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVFnq843\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVFnq843\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VFnq843',
    'container.build_id' => 'a9a4ee57',
    'container.build_time' => 1588477731,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVFnq843');
