<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerQKJYTUm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQKJYTUm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQKJYTUm.legacy');
=======
if (\class_exists(\Container9giQAl3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9giQAl3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9giQAl3.legacy');
>>>>>>> 5c6f0715280772b4616c8815a02c2b87a49fd717

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerQKJYTUm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQKJYTUm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QKJYTUm',
    'container.build_id' => 'a1ff1664',
    'container.build_time' => 1588014981,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQKJYTUm');
=======
    \class_alias(\Container9giQAl3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9giQAl3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9giQAl3',
    'container.build_id' => 'ac20560c',
    'container.build_time' => 1587950245,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9giQAl3');
>>>>>>> 5c6f0715280772b4616c8815a02c2b87a49fd717
